config/routes.rb
Rails.application.routes.draw do
  root 'notes#index'

  resources :my_notes, as: :notes, controller: :notes

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def index
    @notes = get_notes_call.data
  end

  def show
    @note = get_notes_by_id_call(id: params[:id]).data
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/layouts/_navigation.html.slim
nav.top-bar data-topbar="true"
  .top-bar-section
    ul
      = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.slim
li
  = link_to 'Notes', notes_path

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1.0"

    title == content_for?(:title) ? yield(:title) : "Untitled"

    = stylesheet_link_tag "application"
    = javascript_include_tag "vendor/modernizr"
    = csrf_meta_tag

  body

    header
      = render 'layouts/navigation'

    br

    == yield

    = javascript_include_tag "application"

app/views/notes/index.html.slim
.row
  .large-8.columns.large-centered
    table
      caption Notes
      thead
        tr
          th width="50%" Title
          th Content
      tbody
        - @notes.each do |note|
          tr
            td
              = link_to note.title, note_path(note.id)
            td= truncate note.content, length: 100

app/views/notes/show.html.slim
.row
  .large-8.columns.large-centered
    table
      caption Note #{@note.id}
      thead
        tr
          th width="100" Title
          th width="300" Content
      tbody
        tr
          td= @note.title
          td= @note.content